### ISSUE TITLE
Stored mime-type is not served when handling GET requests for uploads

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/plugin-fileuploader#26]

**Comment by vith** [comment]
This is already stored and served by tusd internally:

```console
~/code/kiwi/gopath/src/github.com/kiwiirc/plugin-fileuploader master
❯ jq < uploads/meta/7/e/a/3/2/4/7ea324d31cf4d3c1f5e89a1a4a0fab85.info
{
  "ID": "7ea324d31cf4d3c1f5e89a1a4a0fab85",
  "Size": 6175163,
  "Offset": 0,
  "MetaData": {
    "name": "Screenshot from 2018-05-15 08-34-12.png",
    "type": "image/png"
  },
  "IsPartial": false,
  "IsFinal": false,
  "PartialUploads": null
}
```

https://github.com/tus/tusd/blob/0.10.0/unrouted_handler.go#L547-L548

**Comment by vith** [comment]
There is also a whitelist of mime-types that determines whether `Content-Disposition` is set to `inline` or `attachment` here: https://github.com/tus/tusd/blob/0.10.0/unrouted_handler.go#L572-L597.

Do we need to save the mime-type in the SQL DB as well?

**Comment by prawnsalad** [comment]
Ah.. hm. I guess this isn't working then as if you upload a .png, it is forced to be downloaded rather than displaying in the browser.

**Comment by vith** [comment]
Ah, I am getting the same behavior actually. I'll figure out what's going wrong and fix the existing implementation.

**Comment by vith** [comment]
I've submitted a PR to uppy that fixes this: https://github.com/transloadit/uppy/pull/844

The problem was that uppy sends the mime-type as `type`, but tusd expects it to be keyed as `filetype`.

I tried changing our dependency to point at my fork branch, but yarn is not building it automatically when installed through a git+https URL, possibly because their package.json lacks a `prepare` script. So I will just wait for upstream to accept the change instead.
